Devs
bryanm92s/AppPractica pull request #2
Opened 2022-06-14 22:20 UTC by bryanm92s

Se realizan correciones 

**1.** Se eliminan líneas innecesarias.
**2.** Se implementa Binding en Fragments, Adapters, RecyclerView
**3.** Se implementa Strings, Dimens.
**4.** Se crea fragmento Movie Details.
**5.** Se realizan adecuaciones al diseño de la aplicación.

![Inicio](https://user-images.githubusercontent.com/21268408/173698850-c09ad2c5-8f30-4d98-b964-1bcd895300d8.png)
![Buscar](https://user-images.githubusercontent.com/21268408/173698864-21b4708e-6719-4f35-8205-7ab441e174a8.png)
![Perfil](https://user-images.githubusercontent.com/21268408/173698868-bb1c529b-803c-4eed-becd-d941b7074df8.png)
![MovieDetails](https://user-images.githubusercontent.com/21268408/173698873-af81e5ab-9044-42a1-9921-ab3041f98c57.png)

2022-06-14 22:21 UTC, bryanm92s commented
@jrojas25

2022-06-17 20:42 UTC, jrojas25 requested changes

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/Views/SignUp.kt
>              startActivity(intent)
is always a good practice to finish the current activity when we don't want it to remain in the stack (if we don't do this when the user taps the back button will be redirected to this screen again)

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/Views/SignUp.kt
> +                            if (userObject[i].name?.equals(binding.textInputEditTextNombre.text.toString())!!) {
avoid this validation, and the whole logic of going to the database and get all the users, instead let the database return an error when the user already exists

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/Views/SignUp.kt
> +                            binding.textInputEditTextContrasena.setText("")
move this to its own method, remember the Single Responsibility principle from SOLID

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/adapter/BestMoviesAdapter.kt
> +  }*/
remove the unused code

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/activity_login.xml
>                  android:textSize="20sp"
use dimens

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/activity_login.xml
>                  android:layout_marginStart="32dp"
use dimens

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/activity_login.xml
>                  android:textSize="20sp"
and check the all the other layouts to fix the same

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/fragment_inicio.xml
> +                </RelativeLayout>
avoid nesting layouts and use a constraint layout instead

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/fragment_movie_details.xml
> +        tools:ignore="SpeakableTextPresentCheck,SpeakableTextPresentCheck,TouchTargetSizeCheck,TouchTargetSizeCheck" />
never use the `tools:ignore`

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/fragment_movie_details.xml
> +        <LinearLayout
you're already suing a constraint layout, so there's no need to nest or even use Linear layouts here

2022-06-17 20:42 UTC, jrojas25 commented on app/src/main/res/layout/fragment_perfil.xml
> +                <LinearLayout
don't nest layouts, and don't use other layouts when you're already using constraint layouts

2022-06-30 16:45 UTC, merged