Se implementan nuevas funciones, se elimina código innecesario, se ut…
bryanm92s/AppPractica pull request #5
Opened 2022-06-30 17:33 UTC by bryanm92s

**New features are implemented:**

1. Unnecessary code is removed
2. Binding is used
3. MVVM architecture is implemented in SignUp and Login
4. Coroutines are implemented
5. Design changes are made
6. Variable names are renamed from Spanish to English
7. Dimens and Strings are used

![coroutines](https://user-images.githubusercontent.com/21268408/176741121-98efa99d-1881-46cb-9af8-3e9e695faed0.png)
![englishFragments](https://user-images.githubusercontent.com/21268408/176741122-6f3a7347-8064-4a18-a439-cd4a83529196.png)
![home](https://user-images.githubusercontent.com/21268408/176741125-c559ccbf-847a-4560-acd9-d3d4d9d61381.png)
![mvvm](https://user-images.githubusercontent.com/21268408/176741126-eec70680-d79b-4591-adde-32aa164ad7d5.png)
![play](https://user-images.githubusercontent.com/21268408/176741127-cb55ad29-2c48-49f7-ab4d-ce636a1b3087.png)
![profile](https://user-images.githubusercontent.com/21268408/176741129-dbe0d96c-860a-44dd-8e9e-7571305b3882.png)
![search](https://user-images.githubusercontent.com/21268408/176741131-9def9762-e77f-44d7-b913-f7d9362b79f8.png)

https://user-images.githubusercontent.com/21268408/176741133-69cdd8f6-f420-4b42-b2d5-69f1af6b1bb9.mp4

2022-06-30 17:36 UTC, bryanm92s commented
@jrojas25

2022-07-01 02:13 UTC, jrojas25 requested changes

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/register/RegisterFragment.kt
> +            Log.i("MYTAG", it.toString() + "000000000000000000000000")
what is this for?

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/register/RegisterFragment.kt
> +                registerViewModel.donetoastUserName()
why this should go back to the viewmodel once it gets an update from it?

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/register/RegisterFragment.kt
> +                registerViewModel.donetoastEmail()
why this should go back to the viewmodel once it gets an update from it?

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/register/RegisterFragment.kt
> +                registerViewModel.donetoastPassword()
why this should go back to the viewmodel once it gets an update from it?

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/register/RegisterViewModel.kt
> +            uiScope.launch {
when doing tasks in background avoid using the UI thread

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/java/com/example/apppractica/register/RegisterViewModel.kt
> +    }
what is this for?

2022-07-01 02:13 UTC, jrojas25 commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingBottom="10dp"
use dimens (and check the same for ALL of the layouts)

2022-07-14 13:47 UTC, closed without merging